apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: {{ .Chart.Name }}
    port: 3306
  clusterIP: None

