apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  storageClassName: standard
  volumeName: pv-{{ .Chart.Name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.todoapp.pvc.storage }}