{{- if .Values.todoapp.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ .Chart.Name }}-monitor
    labels:
    {{- range $k, $v := .Values.todoapp.serviceMonitor.labels }}
      {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
    selector:
      matchLabels:
        app: {{ .Chart.Name }}
    endpoints:
    - port: {{ .Values.todoapp.serviceMonitor.port }}
      path: {{ .Values.todoapp.serviceMonitor.path }}
      interval: {{ .Values.todoapp.serviceMonitor.interval }}
{{ end }}